image: node:16.13.1

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g npm@latest
    - npm install
    - npm install --save gh-pages
  artifacts:
    paths:
      - node_modules/

pages:
  stage: deploy
  dependencies: 
    - build
  script:
    - npm run deploy
  artifacts:
    paths:
      - public
  only:
    - main
